### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by tarlepp**
One small clean up

### CODE REVIEW

**Comment by ricknox** [comment]
This scares eslint with asking to add a newline after a import but I think this placement is ok. We should add `// eslint-disable-line import/newline-after-import` at the require line to avoid the error in eslint.

**Comment by tarlepp** [comment]
Fixed linter error

**Comment by tarlepp** [comment]
And fixed also that another linter error - now all is green <3

**Comment by ricknox** [comment]
Thank you @tarlepp.

**Pull request merged**
